name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: FileJanitor

      - name: Clean Output Folders
        run: |
          Remove-Item -Recurse -Force builds\lightweight -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force builds\self-contained -ErrorAction SilentlyContinue
        shell: powershell
        working-directory: FileJanitor

      - name: Publish Framework Dependent Build
        run: dotnet publish -c Release -o builds\lightweight /p:PublishSingleFile=true /p:SelfContained=false
        working-directory: FileJanitor

      - name: Publish Self-Contained Build
        run: dotnet publish -c Release -r win-x64 --self-contained true -o builds\self-contained /p:PublishSingleFile=true
        working-directory: FileJanitor

      - name: Zip Framework Dependent Build
        run: Compress-Archive -Path builds\lightweight\FileJanitor.exe -DestinationPath builds\FileJanitor_lightweight.zip
        shell: powershell
        working-directory: FileJanitor

      - name: Zip Self-Contained Build
        run: Compress-Archive -Path builds\self-contained\FileJanitor.exe -DestinationPath builds\FileJanitor_selfcontained.zip
        shell: powershell
        working-directory: FileJanitor

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            FileJanitor/builds/FileJanitor_lightweight.zip
            FileJanitor/builds/FileJanitor_selfcontained.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
