name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: FileJanitor

      - name: Publish Framework Dependent Build
        run: dotnet publish -c Release -o ../builds/lightweight /p:PublishSingleFile=true
        working-directory: FileJanitor

      - name: Publish Self-Contained Build
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ../builds/self-contained /p:PublishSingleFile=true
        working-directory: FileJanitor

      - name: List contents (for debugging)
        run: |
          echo "Lightweight build contents:"
          dir builds\lightweight
          echo "Self-contained build contents:"
          dir builds\self-contained

      - name: Zip Framework Dependent Build
        run: Compress-Archive -Path builds\lightweight\* -DestinationPath FileJanitor_lightweight.zip

      - name: Zip Self-Contained Build
        run: Compress-Archive -Path builds\self-contained\* -DestinationPath FileJanitor_selfcontained.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            FileJanitor_lightweight.zip
            FileJanitor_selfcontained.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
